version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/pastasMilisenda
      - JWT_SECRET=mi_clave_secreta_super_segura
      - JWT_EXPIRATION=24h
      - ADMIN_EMAIL=admin@milisenda.com
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pastas-network

  mongo:
    image: mongo:latest
    container_name: pastas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pastas-network

volumes:
  mongo_data:

networks:
  pastas-network:
    driver: bridge
